[package]
name = "templates-render"
authors = ["David Krasnitsky <dikaveman@gmail.com>"]
version = "0.1.0"
edition = "2021"
description = "Render a template file"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1"
handlebars = "4"
liquid = "0.26"
regex = "1"
clap = { version = "3",  features = ["derive"] }
serde_json = "1"
